### ISSUE TITLE
None of the default config pack biomes generate.

### ISSUE THREAD

**Issue by MagmaBro123** [Rearth/Origen#5]
Title. Allow both this and the default Overworld pack's biomes to generate.

**Comment by TerdyTheTerd** [comment]
Unfortunantly they are imcompatible with each other out of the box. They both use different distribution methods and Origen uses some custom calculations that the Default Pack does not use. A few months ago I spent several hours merging the two packs with a few minor issues due to the above mentioned details. Now that things have updated I will be revisiting this and seeing if I can achieve the same thing but with perfect results. I would be more than happy to post results once complete. WIth that being said however, there are some biomes from the default pack that I remove, so it really does come to a having to put in the work for a truly custom pack.

**Comment by MagmaBro123** [comment]
Ah, alright.

**Comment by Rearth** [comment]
Stopping most of the default overworld biomes from generating was intentional, as most of them don't quite fit the Origen theme.
