### ISSUE TITLE
Inconsistent Biome Placement - Thin strands of disimalar biomes adjacent to one another

### ISSUE THREAD

**Issue by TerdyTheTerd** [Rearth/Origen#9]
I have been noticing this issue pretty frequently while flying around, I will see sections where there are thin strips of multiple different biomes all next to each other, as seen below, all within 100 blocks there are 4 different biomes...
tall timberland -> badland balconies -> foliage fotress outer -> secluded valley outer
![2024-01-10_21 22 12](https://github.com/Rearth/Origen/assets/9743432/8bff8a06-a140-47c3-a468-8ffc0d118fb4)

Is this a result of any of the customization settings I altered, or is this a known issue? I mostly just increased the cell size and continental scale for larger biomes.

**Comment by Rearth** [comment]
The smaller biome sections are intentional, to make the terrain look a bit more varied and mixed in some areas. What Origen basically does is take some biome, and split it across into multiple smaller ones. I'll soon add an option to disable them, along with some improvements to them as well. In the meantime, you can disable them by setting the _pathwork_* biome weights to 0, or by removing them (in this file here: https://github.com/Rearth/Origen/blob/main/biome-distribution/stages/fill_temperature_zones.yml#L20)
